# Tensors
- Support GPU Acceleration
- Optimize for other DL task  

  
<img src="https://miro.medium.com/v2/resize:fit:800/1*V83L4ydCdk21tXjP22VjXQ.jpeg" width="300px">

In [12]:
import torch

if torch.cuda.is_available():
    torch.device("cuda")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    torch.device("cpu")
    print(f"GPU not available. Using CPU: {torch.get_device}")

Using GPU: NVIDIA GeForce RTX 4050 Laptop GPU


# CreatingTensors

In [45]:
# tensor, empty
torch.tensor([[1,2,3], [0.5, 1, 2]]), torch.empty(2,3)

(tensor([[1.0000, 2.0000, 3.0000],
         [0.5000, 1.0000, 2.0000]]),
 tensor([[2.4829e-24, 7.5390e-43, 4.0000e+00],
         [5.0000e+00, 6.0000e+00, 7.0000e+00]]))

In [43]:
# zeros, ones, rand
torch.manual_seed(100)
torch.zeros(2,3), torch.ones(2,3), torch.rand(2,3)


(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0.1117, 0.8158, 0.2626],
         [0.4839, 0.6765, 0.7539]]))

# ElementWise Operations

In [ ]:
# ElementWise MathsOperation
a = torch.tensor([[1,2,3], [4,5,6]])
b = torch.tensor([[2,3,4], [5,6,7]])

a+2
a-2
a*2
a/2 # converted to float
a//2
a%2
a**2

a+b
a-b
a*b
a/b
b//a
a**b

tensor([[     1,      8,     81],
        [  1024,  15625, 279936]])

In [ ]:
# ElementWise More Operation
a = torch.tensor([[1,2,3], [-4,-5,-6]])

torch.abs(a)
torch.round(a)
torch.negative(a)
torch.ceil(a)
torch.floor(a)
torch.clamp(a, min=2, max=4) # IMP

tensor([[2, 2, 3],
        [2, 2, 2]])

# Matrix Operations

In [65]:
a = torch.randint(size=(2,3), low=0, high=10).float()
b = torch.randint(size=(3,2), low=0, high=10).float()

a,b

(tensor([[8., 3., 3.],
         [5., 0., 6.]]),
 tensor([[4., 0.],
         [8., 4.],
         [7., 2.]]))

In [66]:
m = torch.matmul(a,b)
d = torch.det(m)
i = torch.inverse(m)
mm = torch.matmul(m,i)
m,d,i,mm

(tensor([[77., 18.],
         [62., 12.]]),
 tensor(-192.0000),
 tensor([[-0.0625,  0.0938],
         [ 0.3229, -0.4010]]),
 tensor([[ 1.0000e+00, -4.7684e-07],
         [ 0.0000e+00,  1.0000e+00]]))

In [68]:
v1 = torch.tensor([1,2])
v2 = torch.tensor([3,4])

torch.dot(v1,v2)

tensor(11)

# InPlace Operations

In [76]:
a = torch.randint(size=(2,3), low=-5, high=10).float()
b = torch.randint(size=(2,3), low=-5, high=10).float()

a,b

(tensor([[ 1.,  4., -5.],
         [ 1., -1.,  2.]]),
 tensor([[ 8., -4., -5.],
         [ 7., -4., -3.]]))

In [77]:
a.add_(b)

tensor([[  9.,   0., -10.],
        [  8.,  -5.,  -1.]])

In [ ]:
torch.relu(a), a

(tensor([[9., 0., 0.],
         [8., 0., 0.]]),
 tensor([[  9.,   0., -10.],
         [  8.,  -5.,  -1.]]))

In [79]:
torch.relu_(a), a

(tensor([[9., 0., 0.],
         [8., 0., 0.]]),
 tensor([[9., 0., 0.],
         [8., 0., 0.]]))

# Special Functions

In [80]:
a = torch.randint(size=(2,3), low=-5, high=5).float()
a

tensor([[ 2.,  4., -3.],
        [-1.,  1.,  1.]])

In [ ]:
a.exp(), a.log(), a.sqrt() # a.log uses natural logrithm

(tensor([[7.3891e+00, 5.4598e+01, 4.9787e-02],
         [3.6788e-01, 2.7183e+00, 2.7183e+00]]),
 tensor([[0.6931, 1.3863,    nan],
         [   nan, 0.0000, 0.0000]]),
 tensor([[1.4142, 2.0000,    nan],
         [   nan, 1.0000, 1.0000]]))

In [83]:
a.sigmoid(), a.softmax(dim=0), a.relu()

(tensor([[0.8808, 0.9820, 0.0474],
         [0.2689, 0.7311, 0.7311]]),
 tensor([[0.9526, 0.9526, 0.0180],
         [0.0474, 0.0474, 0.9820]]),
 tensor([[2., 4., 0.],
         [0., 1., 1.]]))

<img src="https://miro.medium.com/v2/resize:fit:1200/0*FrVUd9blFU1SL8RB.png" width="400px"> <img src="https://images.contentstack.io/v3/assets/bltac01ee6daa3a1e14/blte5e1674e3883fab3/65ef8ba4039fdd4df8335b7c/img_blog_image1_inline_(2).png?width=1024&disable=upscale&auto=webp" width="400px">

In [90]:
torch.sigmoid(a), torch.softmax(a, dim=0), torch.relu(a)

(tensor([[0.8808, 0.9820, 0.0474],
         [0.2689, 0.7311, 0.7311]]),
 tensor([[0.9526, 0.9526, 0.0180],
         [0.0474, 0.0474, 0.9820]]),
 tensor([[2., 4., 0.],
         [0., 1., 1.]]))

In [89]:
# Natural logarithm (base e)
torch.log(a)

# Logarithm base 2
torch.log(a) / torch.log(torch.tensor(2.0))

# Logarithm base 10
torch.log(a) / torch.log(torch.tensor(10.0))

tensor([[0.3010, 0.6021,    nan],
        [   nan, 0.0000, 0.0000]])

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfCh3wVYzIRNoyabaJpgUF7eye9FQXJe0PqA&s" width="300px">